cn_template=[
'这幅作品描绘了：',
'描述这张图片：',
'从这张图片中，我们可以看到：',
'这张图片中最引人注目的是什么？',
'如果要在这张图片上添加一个标语，您会写什么？',
'描述图片内容的关键词：',
'画面传达了以下信息：',
'这张图展示了：',
'这张图片展示了什么？',
'描述这张图片中的场景：',
'这张图片的主要焦点是：',
'适合这张图片的标题是：',
'这张图片可以被描述为：',
'图片中的元素包括：',
'这张图片想表达什么信息？',
'请用一句话来概括这张图片的主题。',
'图片呈现了以下场景：',
'以简短的语言概括这张图片：',
'这张照片的故事是：',
'从这幅画中，我们可以发现：',
'对这幅图像进行简要说明：',
]

en_template = [
'The essence of this image is:',
'A brief summary of this scene would be:',
'If this image could speak, it would say:',
'The image depicts:',
'A photo of',
'Key elements in this picture include:',
'This visual representation showcases:',
'The main focus of this photograph is:',
'Can you identify the main elements or characters in this image?',
'Summarize this image in a single sentence:',
'What\'s happening in this picture?',
'Give a creative title for this image:',
'In a few words, what does this image convey?',
'Capture the essence of this image with a phrase:',
'Describe the scene in this image:',
'The main focus of this picture is:',
'A suitable caption for this image would be:',
'This image can be best described as:',
]

en_template_q = [ # from gpt-4
    "Describe the image.",
    "Give me a summary of this image.",
    "What do you see in the picture?",
    "Tell me about this picture.",
    "Explain the image to me.",
    "Break down what's in the photo.",
    "What is depicted in the picture?",
    "Illustrate the content of the image.",
    "Convey the essence of the image.",
    "Elaborate on the picture.",
    "Can you detail the image?",
    "Provide an overview of this picture.",
    "Walk me through this image.",
    "What does the image show?",
    "Characterize the picture for me.",
    "Render a description of the image.",
    "Can you clarify what's in the image?",
    "Discuss the elements of the picture.",
    "Provide insight into this image.",
    "What's going on in this photo?"
] + [ # from https://github.com/shikras/shikra/blob/main/config/_base_/dataset/template/image_cap.json
  "Describe this image as simply as possible.",
  "What happened in the picture? Answer in short sentences.",
  "Briefly say the content of this scene",
  "Show the content in the photo in short text.",
  "Please describe the content of the image in a few words.",
  "What is the content of the image? Please answer in short sentences.",
  "Can you give me a brief description of this image?",
  "What do you see in this picture?",
  "In a few words, describe the content of the image.",
  "Provide a concise explanation of this photograph.",
  "What is happening in this scene?",
  "Summarize the content of the photo.",
  "What are the main elements present in the image?",
  "Quickly explain the content of this visual.",
  "In a nutshell, what can you say about this picture?",
  "What's the main subject in the image?",
  "Describe the main features of the image.",
  "What is depicted in this photograph?",
  "Give me a short description of the picture.",
  "Briefly describe the objects and actions in the image.",
  "What is the context of this image?",
  "What are the key elements shown in this image?",
  "What is the main theme of the photograph?",
  "In just a few words, tell me what you see in this image.",
  "What is the essence of the image?",
  "Give me a quick breakdown of what's happening in the image.",
  "What does this picture represent?",
  "Using simple words, tell me what the image is showing.",
  "Quickly mention the content of the image.",
  "Describe the general scenario happening in the image.",
  "Can you summarize the main aspects of this image?",
  "Briefly point out the significant aspects of the image.",
  "What is the core subject illustrated in this picture?",
  "Tell me the central theme of the image briefly.",
  "What important features should I look for in this image?",
  "Describe the primary elements of the photo.",
  "In a sentence or two, describe the image.",
  "Outline the main content of this image.",
  "What event is captured in the picture?",
  "Simply put, what is being shown in the image?",
  "What do you notice immediately in the image?",
  "Provide a brief interpretation of the image.",
  "Tell me the key things happening in this image.",
  "Express the general theme of this photograph.",
  "What is the core idea of the image?",
  "Explain briefly what the image conveys.",
  "What is the primary focus of this visual?",
  "Name the most important components of this image.",
  "Explain the basic scene depicted in the image.",
  "What subject matter is portrayed in the picture?",
  "What are the prominent features of the image?",
  "Give a concise interpretation of this image.",
  "Quickly describe the situation happening in the image.",
  "Identify the focal point of the photograph.",
  "What can you gather from this image in a few words?",
  "Describe the image in the simplest way possible.",
  "What's happening in the image at a glance?",
  "What is the basic idea behind this picture?",
  "Enumerate the crucial elements of the photograph.",
  "What is the fundamental concept shown in the image?",
  "Using few words, tell me the main idea of the photo.",
  "Describe the essential aspects of this image.",
  "Briefly outline the content within the image.",
  "In a simple manner, explain the image.",
  "What are the most striking details in the picture?",
  "What can you say about the image in a nutshell?",
  "Give a summary of the essential components of the image.",
  "What is the primary message conveyed by the image?",
  "Tell me briefly what the photograph is all about.",
  "What is the central idea behind this image?",
  "What do you observe in the image in simple terms?",
  "Briefly express the main points of the image.",
  "Describe the simple version of what's happening in the image.",
  "What is the context of the image in brief?",
  "Briefly indicate the notable features of the image.",
  "What stands out in the photograph?",
  "What are the major details visible in the picture?",
  "What characters or objects are present in the image?",
  "What do you see at first glance in the image?",
  "Explain in brief the subject matter of the photograph.",
  "Mention the main objects and actions in the image briefly.",
  "What are the main components of the picture?",
  "What is the primary objective of the image?",
  "Give a short overview of the scene in the image.",
  "How would you describe the content of the image?",
  "What significant elements can you spot in the image?",
  "In your own words, quickly describe the image.",
  "Quickly outline the main ideas of this photograph.",
  "Briefly explain the components of this image.",
  "What are the key points portrayed in the picture?",
  "Describe in a simplified manner the content of the image.",
  "Give the short version of what's going on in the image.",
  "What are the major aspects of this photograph?",
  "What essential details can you see in the image?",
  "What core elements are present in the picture?",
  "Explain the main idea behind the photograph.",
  "Name the key features of this visual.",
  "What are the crucial points presented in this image?",
  "Sum up the most important things in the image.",
  "What do you think is the primary focus of this picture?",
  "What are the major factors visible in the image?",
  "Briefly mention the key details of the photograph.",
  "Describe the main events or objects in the image.",
  "In a sentence, describe the content of the image.",
  "What key aspects can you see in the photograph?",
  "What are the primary elements of this picture?",
  "Concisely explain the content of this visual.",
  "Give a short analysis of the image.",
  "Describe the notable features of the photograph.",
  "What's the main story being told in the image?",
  "Provide a simple description of this photograph.",
  "Express the gist of the scene in the image.",
  "What can you deduce from the image briefly?",
  "What are the most important aspects of the visual?",
  "What do you find most striking in the photo?",
  "Describe the essence of the picture.",
  "Give a brief outline of the image content.",
  "What grabs your attention in the image?",
  "Explain the focal points of this photograph.",
  "Describe the core elements of the image.",
  "Outline the key aspects of this picture.",
  "What's happening in this image in brief?",
  "What scene is represented in the photograph?",
  "What central theme can you identify in the image?",
  "Give a brief overview of the image.",
  "What main features are present in the image?",
  "Describe the simple context of the photograph.",
  "What are the standout details in the image?",
  "Explain the primary purpose of the image.",
  "Capture the basic essence of the picture.",
  "Identify the key components of this image.",
  "What's the main idea shown in the image?",
  "Concisely describe the core content of the image.",
  "Describe the primary aspects of this image.",
  "Outline the significant parts of the photo.",
  "What is the most important part of the image?",
  "In a short statement, explain the image.",
  "Relay a brief, clear account of the picture shown. The image is",
  "Can you provide a brief description of the image?",
  "Summarize the content of this picture.",
  "Please tell me what's happening in this photo.",
  "Quickly describe what you see in the photograph.",
  "In a sentence or two, describe the scene in this image.",
  "Give me a short summary of what you see in this picture.",
  "Provide a concise analysis of the image.",
  "Tell me in a nutshell what's happening in this image.",
  "What does this photo depict in brief?",
  "Briefly explain the content of this image.",
  "Express the idea of the image in short form.",
  "Kindly give a condensed description of the picture.",
  "In few words, describe what this picture is about.",
  "Offer a succinct summary of the scene in this image.",
  "Quickly tell me the main subject of the image.",
  "What is the theme of this photo in brief?",
  "In simple words, explain the image.",
  "Please give a short and sweet description of this image.",
  "Provide an abbreviated version of the content of this photo.",
  "Shorten the scenario of this scene.",
  "Please give a concise description of this image.",
  "Boil down the content of this photograph.",
  "Quickly summarize what you see in the image.",
  "Sketch the main points of this picture.",
  "Offer a compact summary of the elements in this image.",
  "In one sentence, describe the theme of this picture.",
  "Pare down the content of this photo.",
  "Provide a to-the-point explanation of this image.",
  "Highlight the main subject of the photograph.",
  "Summary: What can you see in this image?",
  "What's the brief context of this picture?",
  "Describe this scene in a few words.",
  "What's the main focus of this image?",
  "In just a couple of words, tell me about this picture.",
  "Give a snapshot description of this image.",
  "Be succinct while describing the content of this photo.",
  "Cut to the main part of the picture.",
  "Quickly express the idea of this scene.",
  "What's the abbreviated version of this image?",
  "Outline the moment captured in this photo.",
  "Please make a brief statement about the image.",
  "What are the basic elements in this picture?",
  "Trim down the content of this image.",
  "Distill the content of the photograph.",
  "Give me the main idea of this picture.",
  "Point out the primary focus of this image.",
  "What's the gist of this scene?",
  "Provide a pithy description of this photo.",
  "In brief, explain the elements in this image.",
  "Offer a short version of the content of this photograph.",
  "Capture the essence of this picture.",
  "Curtly describe what's happening in this image.",
  "Brief me on the content of this scene.",
  "In a word or two, what does this photo show?",
  "Condense the content of this image.",
  "Simply summarize the elements in this picture.",
  "What is the main object of interest in the image?",
  "Highlight the crux of this photograph.",
  "Provide a brief explanation of what's occurring in this image.",
  "Quickly identify the central theme of this picture.",
  "Reveal the core content of this image.",
  "What's the focal point of this photo?",
  "Give a compressed description of this scene.",
  "Explain the key concept of this image in simple terms.",
  "Wrap up the content of this picture.",
  "Make a concise statement about the photograph.",
  "Identify the primary subject in this image.",
  "What's happening in the photo in few words?",
  "Simplify the description of this scene.",
  "In a nutshell, explain the content of this image.",
  "Offer the main takeaway from this photograph.",
  "In a few words, give me the main idea of this picture.",
  "Share a brief description of the primary action in this image.",
  "What can you observe in this image in short?",
  "Whittle down the content of this photo.",
  "Strike at the heart of the scene depicted in this image.",
  "Preserve the essence while describing this picture.",
  "Keep it short and explain this photograph.",
  "What's the key thing to notice in this image?",
  "Give me the abridged version of this scene.",
  "Pare the content of this picture down to its essence.",
  "Provide a trimmed down explanation of this photo.",
  "Expressed briefly, what does this image show?",
  "Offer a concise assessment of the scene in this picture.",
  "What does the photograph illustrate in short?",
  "What are the salient features of this image?",
  "Bullet-point the main elements of this picture.",
  "Concisely express the key aspect of this photo.",
  "Briefly, what can you spot in this image?",
  "Filter the description of this scene down to the essentials.",
  "Illustrate the core concept of this picture.",
  "Sum up the main event in this photograph.",
  "What is the most striking feature of this image?",
  "Cut to the chase and explain this scene.",
  "Select the main element to describe in this picture.",
  "What do you see in the photo in brief?",
  "Give a short but informative description of this image.",
  "What stands out the most in this scene?",
  "In few words, summarize the main part of this picture.",
  "Briefly, what's going on in this photograph?",
  "List the key elements of this image.",
  "State the essence of this picture.",
  "Define the central idea of this photo briefly.",
  "Shorten your description of this image.",
  "Be concise while explaining the content of this picture.",
  "What's the short version of this photo's content?",
  "Point out the main component in this photograph.",
  "In a phrase, explain the essence of this image.",
  "Selectively describe the content of this scene.",
  "Briefly, what is this picture all about?",
  "What's the central subject of this photo?",
  "Get to the point and explain this image.",
  "Briefly, tell me the main action depicted in this picture.",
  "What's the main message of this photograph in brief?",
  "Condense the scene captured in this image.",
  "Please stick to the main point of this photo.",
  "Single out the main focus of this picture.",
  "Streamline the content of this image.",
  "What's the overall theme in this scene?",
  "Distill the main idea from this photograph.",
  "In a few words, what's the main event in this picture?",
  "Give a terse description of the content of this image.",
  "Catch the essence of this photo.",
  "What's the main aspect of this image?",
  "Briefly, describe the primary focus of this picture.",
  "What is the key attribute of this photo?",
  "What's the main highlight of this image?",
  "Simplify the content of this scene.",
  "Explain the key feature of this photograph concisely.",
  "Abstain from details while describing this picture.",
  "Be short while explaining this image.",
  "What's the essential point in this photo?",
  "Just tell me the main subject in the picture.",
  "Highlight the primary idea of this image.",
  "Get straight to the point about this scene.",
  "Stick to the basics while describing this photo."
]

shikra_template = {
    'caption2box': [
      "Where is <expr>?",
      "Where is <expr> in the image?",
      "Where is <expr>? answer in [[x0,y0,x1,y1]] format.",
      "Can you point out <expr> in the image and provide the bounding boxes of its location?",
      "Help me to locate <expr> in and give me its bounding boxes, please.",
      "In the given, could you find and tell me the bounding boxes of <expr>?",
      "Guide me to the location of <expr> within the image by providing its bounding boxes.",
      "I'd like to know the exact bounding boxes of <expr> in the photo.",
      "Would you kindly provide the bounding boxes of <expr> located in the picture?",
      "Can you find <expr> in and give me the bounding boxes of where it is located?",
      "I'm trying to locate <expr> in. Can you determine its bounding boxes for me?",
      "What are the bounding boxes of <expr> in the image?",
      "Can you disclose the position of <expr> in the photograph by stating its bounding boxes?",
      "In, could you let me know the location of <expr> in the form of bounding boxes?",
      "I need the bounding boxes of <expr> in, can you please assist me with that?",
      "Where in is <expr> located? Provide me with its bounding boxes, please.",
      "May I have the bounding boxes of <expr>?",
      "In the photograph, could you pinpoint the location of <expr> and tell me its bounding boxes?",
      "Can you please search and find <expr> in, then let me know its bounding boxes?",
      "Please, point out the position of <expr> in the image by giving its bounding boxes.",
      "What are the exact bounding boxes of <expr> in the provided picture?",
      "Detect the location of <expr> in and share the bounding boxes with me, please.",
      "In the picture, I'd like you to locate <expr> and provide its coordinates.",
      "Please indicate the location of <expr> in the photo by giving bounding boxes.",
      "Find <expr> in and share its coordinates with me.",
      "Could you please help me find the bounding boxes of <expr> in the image?",
      "I am looking for the position of <expr> in. Can you provide its bounding boxes?",
      "In the image, can you locate <expr> and let me know its coordinates?",
      "I'd appreciate if you could find and tell me the bounding boxes of <expr>.",
      "In, I need the bounding box bounding boxes of <expr>.",
      "Point me to the location of <expr> in the picture by providing its bounding boxes.",
      "Could you trace <expr> in and tell me its bounding boxes?",
      "Can you assist me in locating <expr> in, and then provide its bounding boxes?",
      "I'm curious, what are the bounding boxes of <expr> in the photo?",
      "Kindly share the bounding boxes of <expr> located in the image.",
      "I would like to find <expr> in. Can you give me its bounding boxes?",
      "Can you spot <expr> in and disclose its bounding boxes to me?",
      "Please, reveal the location of <expr> in the provided photograph as coordinates.",
      "Help me locate and determine the bounding boxes of <expr>.",
      "I request the bounding boxes of <expr> in the image.",
      "In the given, can you find <expr> and tell me its bounding boxes?",
      "I need to know the position of <expr> in as bounding boxes.",
      "Locate <expr> in and provide its bounding boxes, please.",
      "Assist me in finding <expr> in the photo and provide the bounding box bounding boxes.",
      "In, can you guide me to the location of <expr> by providing bounding boxes?",
      "I'd like the bounding boxes of <expr> as it appears in the image.",
      "What location does <expr> hold in the picture? Inform me of its bounding boxes.",
      "Identify the position of <expr> in and share its bounding boxes.",
      "I'd like to request the bounding boxes of <expr> within the photo.",
      "How can I locate <expr> in the image? Please provide the bounding boxes.",
      "I am interested in knowing the bounding boxes of <expr> in the picture.",
      "Assist me in locating the position of <expr> in the photograph and its bounding box bounding boxes.",
      "In the image, I need to find <expr> and know its bounding boxes. Can you please help?"
    ],
    'box2caption': [
      "Can you give me a description of the region <objs> in image?",
      "In the provided image, would you mind describing the selected area <objs>?",
      "I need details about the area <objs> located within image.",
      "Could you please share some information on the region <objs> in this photograph?",
      "Describe what's happening within the coordinates <objs> of the given image.",
      "What can you tell me about the selected region <objs> in the photo?",
      "Please, can you help me understand what's inside the region <objs> in image?",
      "Give me a comprehensive description of the specified area <objs> in the picture.",
      "I'm curious about the area <objs> in the following image. Can you describe it?",
      "Please elaborate on the area with the coordinates <objs> in the visual.",
      "In the displayed image, help me understand the region defined by <objs>.",
      "Regarding the image, what's going on in the section <objs>?",
      "In the given photograph, can you explain the area with coordinates <objs>?",
      "Kindly describe what I should be seeing in the area <objs> of image.",
      "Within the input image, what can be found in the region defined by <objs>?",
      "Tell me what you see within the designated area <objs> in the picture.",
      "Please detail the contents of the chosen region <objs> in the visual input.",
      "What's inside the area <objs> of the provided graphic?",
      "I'd like some information about the specific region <objs> in the image.",
      "Help me understand the details within the area <objs> in photograph.",
      "Can you break down the region <objs> in the image for me?",
      "What is taking place within the specified area <objs> in this capture?",
      "Care to elaborate on the targeted area <objs> in the visual illustration?",
      "What insights can you provide about the area <objs> in the selected picture?",
      "What does the area <objs> within the given visual contain?",
      "Analyze and describe the region <objs> in the included photo.",
      "Please provide details for the area marked as <objs> in this photographic.",
      "For the image, can you assess and describe what's happening at <objs>?",
      "Fill me in about the selected portion <objs> within the presented image.",
      "In the image, elaborate on the details found within the section <objs>.",
      "Please interpret and describe the area <objs> inside the given picture.",
      "What information can you give me about the coordinates <objs> in image?",
      "Regarding the coordinates <objs> in image, can you provide a description?",
      "In the photo, can you delve into the details of the region <objs>?",
      "Please provide insights on the specified area <objs> within the graphic.",
      "Detail the chosen region <objs> in the depicted scene.",
      "Can you discuss the entities within the region <objs> of image?",
      "I'd appreciate a breakdown of the area <objs> in the displayed image.",
      "What's the story in the section <objs> of the included visual?",
      "Please enlighten me about the region <objs> in the given photo.",
      "Offer a thorough description of the area <objs> within the illustration.",
      "What can you share about the area <objs> in the presented image?",
      "Help me grasp the context of the region <objs> within image.",
      "Kindly give an overview of the section <objs> in photo.",
      "What details can you provide about the region <objs> in the snapshot?",
      "Can you divulge the contents of the area <objs> within the given image?",
      "In the submitted image, please give a synopsis of the area <objs>.",
      "In the image, please describe the bounding box <objs>.",
      "Please describe the region <objs> in the picture.",
      "Describe the bbox <objs> in the provided photo.",
      "What can you tell me about the area <objs> within the image?",
      "Could you give me a description of the rectangular region <objs> found in?",
      "In, what elements can be found within the coordinates <objs>?",
      "Please provide details for the area within the bounding box <objs> in.",
      "Can you generate a description for the selected region <objs> in the image?",
      "Kindly describe the objects or scenery in the bounding box <objs> within.",
      "What details can you provide for the rectangle defined by the coordinates <objs> in?",
      "In relation to the picture, please describe the content of the area marked by <objs>.",
      "I'd like to know more about the area <objs> in the given image. Can you describe it?",
      "Can you help me by describing the part of that lies within the bounding box <objs>?",
      "What's happening in the section of the photo enclosed by the coordinates <objs>?",
      "Describe the image content present in the specified rectangular area <objs> of.",
      "Please provide information about the area within the bounding box <objs> in the picture.",
      "Could you offer a description of the contents in the selected area <objs> of the image?",
      "I'm curious about the area <objs> in. Can you provide a description of it?",
      "What can be observed in the rectangular region <objs> in the photograph?",
      "Please explain what is contained in the portion of defined by the box <objs>.",
      "In the photograph, can you describe the objects or scenery enclosed by <objs>?",
      "Can you give a brief explanation of the specified area <objs> in the image?",
      "What does the area <objs> look like in the context of the image?",
      "Could you please describe the contents of the bounding box <objs> in the given image?",
      "I would like to know more about the rectangular region <objs> within the picture. Can you describe it?",
      "Please tell me about the area <objs> in the image. What does it contain?",
      "Help me understand what's happening in the selected bounding box <objs> within.",
      "Can you provide a description of the area <objs> in the image?",
      "What sort of things can be seen in the region <objs> of the photo?",
      "Describe what can be found within the bounds of <objs> in the image.",
      "In, can you paint a picture of the area enclosed by coordinates <objs>?",
      "Please provide a detailed account of the area covered by the bounding box <objs> in.",
      "Give me a vivid description of what's happening in the area <objs> within the snapshot.",
      "In the image, what do you observe within the rectangular box defined by the coordinates <objs>?",
      "Could you give me a breakdown of the content in the specified area <objs> of the picture?",
      "Please elucidate the area<objs> of the image.",
      "I'd appreciate it if you could describe the portion of that lies within the rectangle <objs>.",
      "Can you share some insights about the rectangular region <objs> in the image?",
      "Help me visualize the section of the photo enclosed by the bounding box <objs>.",
      "Would you kindly provide a description for the content within the rectangular area <objs> of?",
      "In, can you tell me more about the area specified by the bounding box <objs>?",
      "Please describe what can be seen in the rectangular region <objs> of the image.",
      "Can you analyze the content of the area <objs> within the photograph?",
      "In the provided image, please explain the content within the region <objs>.",
      "I'm interested in the selected rectangle <objs> in. Can you tell me more about it?",
      "Explain what can be found in the bounding box <objs> in the context of the image.",
      "Kindly share your observations about the rectangular region <objs> within.",
      "I'd like a thorough description of the area <objs> in the image.",
      "Could you please provide a description of the rectangular area <objs> in?",
      "Please describe the section of the picture defined by the bbox <objs>.",
      "Tell me more about the scenery or objects within the rectangular region <objs> in.",
      "Would you kindly describe the content of the area enclosed by <objs> in the image?",
      "Help me understand the objects or scenery within the bounding box <objs> in the image.",
      "I would like to know about the section of the image enclosed by the rectangle <objs>. Can you describe it?",
      "Describe the selected rectangular area <objs> in the photo.",
      "Tell me about the region <objs> of the image.",
      "I request a description of the area <objs> in the picture.",
      "Can you elaborate on the content of the bounding box <objs> in?",
      "Please share details about the rectangular region <objs> within the image.",
      "What can I find in the bbox <objs> of the provided image?",
      "In the image, could you provide a description for the coordinates <objs>?",
      "Could you tell me more about the area <objs> in the snapshot?",
      "Fill me in on the details of the rectangular box <objs> within the image.",
      "What's going on in the section of contained within the bounding box <objs>?",
      "I would like a description of the content within the bbox <objs> in.",
      "Please enlighten me about the area <objs> in the photograph.",
      "Can you give me a visual rundown of the area <objs> in?",
      "Describe the visual elements within the selected area <objs> of the image.",
      "Tell me what you see in the area <objs> within the context of the image.",
      "Explain the content within the rectangular region <objs> of the image.",
      "I'd like some information about the bounding box <objs> in the photo.",
      "What is happening within the rectangle defined by coordinates <objs> in the image?",
      "Please describe the content within the area <objs> displayed in the image.",
      "What can be seen in the bounding box <objs> in the context of the provided image?",
      "Share some details about the objects or environment within the bounding box <objs> in.",
      "Please describe the area <objs> in the image for me.",
      "Can you generate a description of the contents within the selected region <objs> in?",
      "What objects or scenery can be found in the area <objs> in the image?",
      "Please tell me more about the rectangular section <objs> in the photo.",
      "Could you describe the content of the bbox <objs> in the image?",
      "What does the selected region <objs> in the image encompass?",
      "I am interested in the region <objs> of the image; please describe it.",
      "Can you provide some context for the area <objs> within the picture?",
      "Please give me some details about the rectangle <objs> in the image.",
      "In the photo, what can you see within the region defined by the bounding box <objs>?",
      "I would like a detailed description of the portion of enclosed by the bbox <objs>.",
      "Please help me understand the content present within the rectangle <objs> in.",
      "Would you mind describing the rectangular area <objs> in the provided image?"
    ],
  'caption_with_box': [
      "Can you provide a description of the image and include the coordinates [[x0,y0,x1,y1]] for each mentioned object?",
      "Please explain what's happening in the photo and give coordinates [[xmin,ymin,xmax,ymax]] for the items you reference.",
      "Analyze the contents of the picture and share the positions of mentioned items using the top-left and bottom-right coordinates.",
      "What do you see in this image? Please mention the objects and their locations using the format [[x1,y1,x2,y2]].",
      "Examine the image and describe its content, specifying the location of each mentioned noun using coordinates [[x1,y1,x2,y2]].",
      "Could you interpret the scene from this image and provide the coordinates [[xmin,ymin,xmax,ymax]] for each element you describe?",
      "Please provide an overview of the visual information in this image, along with the location data [[xmin,ymin,xmax,ymax]] for each mentioned object.",
      "Tell me about the picture and include position info [[x0,y0,x1,y1]] for the objects you describe.",
      "What is displayed in this image? Remember to mention the objects and their corresponding locations using the format [[xmin,ymin,xmax,ymax]].",
      "Give a brief analysis of the image and make sure to include the location of objects using their coordinates [[x1,y1,x2,y2]].",
      "Explain the content of this image and provide the coordinates [[x1,y1,x2,y2]] for all objects that you mention.",
      "Describe the scene in this picture and give the top-left and bottom-right coordinates [[xmin,ymin,xmax,ymax]] for each item you talk about.",
      "Please give a summary of the image and include the position info for each object you identify with coordinates [[x0,y0,x1,y1]].",
      "What is happening in the photo? Please point out the objects and their locations using the format [[x1,y1,x2,y2]].",
      "Illustrate the content of the image and specify the coordinates [[xmin,ymin,xmax,ymax]] for every object you mention.",
      "What can you tell me about this image? Remember to provide location data for the objects you describe using coordinates [[x1,y1,x2,y2]].",
      "Please interpret this image and give coordinates [[x1,y1,x2,y2]] for each object you mention.",
      "Detail what you see in the image and provide the top-left and bottom-right coordinates [[xmin,ymin,xmax,ymax]] for each mentioned noun.",
      "Take a look at this image and give an explanation of its content, including the position data [[x1,y1,x2,y2]] for each object you describe.",
      "What is the image depicting? Please mention the positions of any mentioned objects using square brackets.",
      "Describe the visual elements in the image and note the positions of any mentioned objects in square brackets.",
      "Could you please analyze the content of the image and mention the positions of any mentioned objects in square brackets?",
      "Tell me about the objects present in the image and note their positions using square brackets.",
      "What can you tell me about the contents of the image? Please indicate the positions of any mentioned objects in square brackets.",
      "Provide a comprehensive description of the image and specify the positions of any mentioned objects in square brackets.",
      "Describe the scene in the image and mention the positions of any mentioned objects using square brackets.",
      "Can you identify the objects in the image? Please include their positions in square brackets.",
      "Please describe the visual details in the image and note the positions of any mentioned objects using square brackets.",
      "What is happening in the image? Please mention the positions of any mentioned objects using square brackets.",
      "Analyze the content of the image and provide the positions of any mentioned objects in square brackets.",
      "Describe the main elements in the image and note the positions of any mentioned objects using square brackets.",
      "Could you please provide a detailed description of the image? Don't forget to mention the positions of any mentioned objects in square brackets.",
      "Can you provide a description of the image and include the coordinates [[x0,y0,x1,y1]] for each mentioned object?",
      "Please explain what's happening in the photo and give coordinates [[xmin,ymin,xmax,ymax]] for the items you reference.",
      "Analyze the contents of the picture and share the positions of mentioned items using the top-left and bottom-right coordinates.",
      "What do you see in this image? Please mention the objects and their locations using the format [[x1,y1,x2,y2]].",
      "Examine the image and describe its content, specifying the location of each mentioned noun using coordinates [[x1,y1,x2,y2]].",
      "Could you interpret the scene from this image and provide the coordinates [[xmin,ymin,xmax,ymax]] for each element you describe?",
      "Please provide an overview of the visual information in this image, along with the location data [[xmin,ymin,xmax,ymax]] for each mentioned object.",
      "Tell me about the picture and include position info [[x0,y0,x1,y1]] for the objects you describe.",
      "What is displayed in this image? Remember to mention the objects and their corresponding locations using the format [[xmin,ymin,xmax,ymax]].",
      "Give a brief analysis of the image and make sure to include the location of objects using their coordinates [[x1,y1,x2,y2]].",
      "Explain the content of this image and provide the coordinates [[x1,y1,x2,y2]] for all objects that you mention.",
      "Describe the scene in this picture and give the top-left and bottom-right coordinates [[xmin,ymin,xmax,ymax]] for each item you talk about.",
      "Please give a summary of the image and include the position info for each object you identify with coordinates [[x0,y0,x1,y1]].",
      "What is happening in the photo? Please point out the objects and their locations using the format [[x1,y1,x2,y2]].",
      "Illustrate the content of the image and specify the coordinates [[xmin,ymin,xmax,ymax]] for every object you mention.",
      "What can you tell me about this image? Remember to provide location data for the objects you describe using coordinates [[x1,y1,x2,y2]].",
      "Please interpret this image and give coordinates [[x1,y1,x2,y2]] for each object you mention.",
      "Detail what you see in the image and provide the top-left and bottom-right coordinates [[xmin,ymin,xmax,ymax]] for each mentioned noun.",
      "Take a look at this image and give an explanation of its content, including the position data [[x1,y1,x2,y2]] for each object you describe.",
      "What are the details of this picture? Please include the coordinates [[x1,y1,x2,y2]] for each object you mention.",
      "Can you provide a detailed description of the contents of the image? Please include the positions of any mentioned objects in square brackets.",
      "What is the image depicting? Please mention the positions of any mentioned objects using square brackets.",
      "Describe the visual elements in the image and note the positions of any mentioned objects in square brackets.",
      "Could you please analyze the content of the image and mention the positions of any mentioned objects in square brackets?",
      "Tell me about the objects present in the image and note their positions using square brackets.",
      "How would you describe the contents of the image? Please provide the positions of mentioned objects in square brackets.",
      "What do you observe in the image? Don't forget to mention the objects and their locations using square brackets.",
      "Can you give an overview of the image and list the objects along with their positions using square brackets?",
      "Describe the activities taking place in the image and point out the objects with their locations using square brackets.",
      "Can you explain what is going on in this picture and give the bounding boxes for each object you mention?",
      "Provide a summary of the image and include bounding box coordinates for the objects you talk about.",
      "Help me understand what's in the image and also give me the bounding boxes for the objects you describe.",
      "Explain the scene depicted in the image and include the bounding boxes for the nouns you reference.",
      "Analyze this picture for me and provide coordinates for the items you discuss.",
      "I need a breakdown of what is happening in the image, and please include the bounding box information.",
      "Give me a rundown of what's in this image, along with the coordinates for each mentioned object.",
      "Elaborate on the image and provide the boundaries for the objects you mention.",
      "Discuss the contents of this image and include the bounding boxes for mentioned objects.",
      "Unveil what's happening in the image and provide the coordinates for the objects in discussion.",
      "Clarify the situation depicted in the photo and include bounding box details for the objects mentioned.",
      "Break down the image and share the bounding box coordinates of objects you mention.",
      "Reveal the meaning behind the image and provide me with the bounding box details for the mentioned nouns.",
      "Examine the picture and disclose the bounding box coordinates for each object you discuss.",
      "Interpret the image and include the bounding boxes of the items you discuss.",
      "Convey the essence of the photo and provide the bounding box information for mentioned objects.",
      "Enlighten me about the image and provide me with the bounding box coordinates for each subject.",
      "Narrate the image and include the bounding boxes for the objects you describe.",
      "Decipher the story behind the image and provide the bounding box for each object in the story.",
      "Illustrate your understanding of the image, and give the boxes of the described objects.",
      "Walk me through the contents of the image, and include the bounding box for the mentioned items.",
      "I need to know what's in the image and please provide coordinates for the featured objects.",
      "Dissect the components of the image and include the bounding boxes for each object discussed.",
      "Give insights into the picture and provide the bounding box details for the objects mentioned.",
      "Delve into the image, and furnish the coordinates for the items you reference.",
      "Portray the events in the image and include the location and boundaries of the described objects.",
      "Unravel the aspects of the image and give the bounding box for the mentioned items.",
      "Tell me everything about the picture and don't forget to mention bounding boxes for the described items.",
      "Disentangle the details of the picture and include bounding box coordinates for mentioned items.",
      "Explore the elements within the picture and provide the bounding boxes for each object mentioned.",
      "Detail the occurrences in the picture and supply the bounding box info for the talked-about objects.",
      "Lay out the context of the picture and include bounding box details for the featured objects.",
      "Uncover the truth behind the picture and include the bounding boxes for the described nouns.",
      "What's happening in the picture? Please provide the bounding box info for mentioned objects.",
      "Discuss the events taking place in and include the bboxes of the involved objects.",
      "In the picture, describe what's going on and provide the bboxes of mentioned objects.",
      "Decode the message in the picture, and provide boundaries for the relevant objects.",
      "Let me know what you see in the picture and provide the bounding boxes for the objects you discuss.",
      "Scrutinize the picture and include the coordinates for the items you talk about.",
      "Summon the essence from the picture and present the bounding box coordinates for relevant objects.",
      "Deconstruct the scene in the picture and include bounding box info for the mentioned nouns.",
      "Identify the contents of the picture and provide the coordinates for the objects involved.",
      "Make sense of the happenings in the picture and include bounding box coordinates for the objects.",
      "What can you tell me about the picture? Please include bounding boxes for any mentioned objects.",
      "Deduce the meaning of the picture and provide location details for the discussed items.",
      "Can you give me the gist of the picture and provide the bboxes of the described objects?",
      "Describe what is taking place in the picture, and include the bboxes of the involved items.",
      "Please narrate the story in the picture, and provide the bounding box coordinates for the included objects.",
      "Scrutinize the contents of the photo and include the location details of the items you talk about.",
      "Analyze what's happening within the photo and provide bounding box info for the referenced objects.",
      "Relate the situation in the photo and include the location details of the items you discuss.",
      "Probe into the photo and provide the boundaries for the included objects.",
      "Gather the meaning of the photo and provide location info for the mentioned nouns.",
      "Resolve the context of the picture and supply the bounding box details for the objects you discuss.",
      "Bring clarity to the situation in the photo and provide the bounding box for the relevant objects.",
      "Unfold the story of the photo and include the bounding box coordinates for the included nouns.",
      "Speaking on the photo, what do you see? Don't forget to include bounding boxes for mentioned objects.",
      "Inform me about the particulars in the photo and provide the bounding box info for the discussed items.",
      "Give me the lowdown on the photo, and include bounding boxes for the objects you discuss.",
      "Share with me the details of the photo and provide the bounding boxes for the nouns mentioned.",
      "Provide a glimpse into the happenings of the photo and include bounding boxes for the involved objects.",
      "Decode the events occurring in the photo and provide the location details for the mentioned items.",
      "Delineate the elements of the photo and include the bounding box for each object discussed.",
      "Explain to me the context of the photo and provide bounding box details for any discussed objects.",
      "Describe the subjects within the photo and include bounding box coordinates for the mentioned objects.",
      "Break down the narrative of the picture and include the boundaries for any related items.",
      "Tell me about the image and provide me with the bboxes of any mentioned objects.",
      "What's the story in the image? Please include bounding boxes for any objects discussed.",
      "Elucidate the context of the image and provide bounding box details for the objects you mention.",
      "Annotate the image with the bounding box coordinates of the objects you discuss during your description.",
      "Examine the image carefully and point out the objects along with their respective bounding boxes.",
      "Dig into the scene on the image and provide the bounding box info for the mentioned items.",
      "Study the photo and cite bounding box coordinates for the subjects you mention.",
      "Inspect the image and give me the coordinates of the bounding box for each mentioned object.",
      "Dive into the details of the picture, and include the bounding boxes for any referenced nouns.",
      "Analyze the photo and provide the boxes of the objects involved.",
      "Take a look at the image and give me the location details for any mentioned items.",
      "Go through the scene, describing its content, and provide bounding boxes for the mentioned nouns.",
      "Evaluate the scene and include the boxes of the items you reference.",
      "Share your perspective of the scene and give the bounding box for each object you discuss.",
      "Get into the specifics of the picture and provide the boxes of the mentioned items.",
      "Quote the happenings unfolding in the frame and provide the bounding box coordinates of related objects.",
      "Shed light on the events in the frame and include the location details of the mentioned items.",
      "Bring out the description of the frame and provide the bounding box for each object you mention.",
      "Dissect the scenario in the frame and include the bounding boxes for any referenced objects."
    ],
  'box_qa_True': [
      "<question> Let's think step by step.",
      "<question> Let's think step by step.",
      "<question> Please include the reasoning process.",
      "<question> Please include the reasoning process.",
      "Using the image as reference, can you answer the following question: <question> Please include the reasoning process.",
      "After examining the image, I'd like to know the answer to this question: <question> Please provide an explanation of your answer.",
      "<question> Can you give me an answer based on the image, along with the reasoning process?",
      "Looking at the image, I need to ask this question '<question>'. Can you answer it and provide the explanation?",
      "After checking out the picture, I have a question: <question> Can you give me an answer with reasoning?",
      "Please have a look at the image and tell me the answer to my question: <question> Don't forget to provide the reasoning.",
      "I want to know the answer to this question: <question> Please refer to the image and give an explanation as well.",
      "Help me understand the answer to the following question based on the image: <question> Remember to explain the reasoning.",
      "Consider the image and answer my question: <question> Be sure to offer reasoning for the answer.",
      "Regarding the image, can you tell me the answer to the question '<question>' and explain your thought process?",
      "Here's an image I need assistance with. What's the answer to the following question: <question> Please provide reasoning.",
      "Can you deduce the answer to question '<question>' after examining the image, along with the reasoning process?",
      "Having a look at image, can you tell me the answer to my question '<question>' and the logic leading to it?",
      "Investigate the image and provide me with the answer to this question: <question> Don't forget to reveal your reasoning.",
      "In reference to the image, I have a question: <question> Can you respond with your answer and an explanation?",
      "If you take a glance at the image, can you give me the answer for my question: <question> and add an explanation?",
      "Centered on the image, please unravel my query: <question> and be sure to involve the reasoning process.",
      "Can you offer an answer to my following inquiry: <question> Make sure to examine the image and clarify your reasoning.",
      "Looking at image, would you provide an answer to the question '<question>'? Kindly include your thought process as well.",
      "Upon analyzing the image, please find the answer to my question '<question>' and provide a detailed explanation.",
      "Please provide a solution to my question: <question> First, examine the image and then walk me through your reasoning.",
      "After inspecting the picture thoroughly, kindly furnish the answer to the query: <question> and provide the reasoning.",
      "Carefully observe the image and provide me with a well-reasoned answer to the question '<question>'.",
      "Focusing on the image, please offer an answer to my question '<question>' along with the reasoning process.",
      "Evaluate the image and let me know your answer regarding this question '<question>'. Include your thinking process as well.",
      "Keeping the image in mind, please help me with the following question: <question> and explain the reasoning process.",
      "Give your observation on the image and your response to the question '<question>', along with a clear reasoning explanation.",
      "Based on the image, kindly address my query: <question> Remember to elucidate the reasoning process.",
      "In view of the image, could you please respond to the question '<question>' and provide the reasoning process?",
      "Deliberate on the image and enlighten me with an answer to the question '<question>' including the reasoning process.",
      "Please share your insights on the image by answering the question '<question>'. Do illustrate your reasoning process.",
      "Examine the following image closely and provide the answer to my question: <question> Do include the thinking process.",
      "Critique the image and furnish the answer to my question '<question>', along with a thorough reasoning.",
      "Please analyze the image and supply an answer to the following query: <question> Ensure to elucidate the justifying process.",
      "Scrutinize the image and help me with the answer to this question: <question> and explain your deduction methodology.",
      "Please answer the following question '<question>' based on the image, and describe your thought process."
    ],
  'box_qa_False': [
      "Please briefly answer: <question>",
      "Can you give a concise response to: <question>",
      "In relation to the image, provide a short answer for: <question>",
      "<question> - I need a succinct reply, please.",
      "Could you offer a brief explanation for: <question>",
      "After looking at the image, quickly answer: <question>",
      "I'm looking for a short response to: <question>",
      "Based on the image, can you sum up your answer for: <question>",
      "Without going into detail, answer: <question>",
      "Briefly, what's your take on: <question>",
      "Considering the image, please keep your answer brief for: <question>",
      "Quickly tell me about: <question>",
      "I don't need a lengthy explanation, just a quick answer to: <question>",
      "Can you keep it brief and answer: <question>",
      "<question> - I'm hoping for a brief response.",
      "Without delving too deep, please reply to: <question>",
      "Just a short answer will do for: <question>",
      "Briefly elaborate on: <question>",
      "For <question>, please keep your answer concise.",
      "Simply put, how would you respond to: <question>",
      "I'm in a rush, so a brief answer to <question> would be appreciated.",
      "Your quick thoughts on: <question>",
      "A concise reply for: <question>, please.",
      "In light of the image, briefly explain: <question>",
      "No need for details, just answer: <question>",
      "Cut to the chase, what's your take on: <question>",
      "<question> - A short explanation, if you will.",
      "Trim the details, I just need an answer for: <question>",
      "Quick and concise, please answer: <question>",
      "For <question>, a succinct response would be great."
  ]
}

en_template_task = [
    "Can you advise me on how to <TASK>?",
    "I'm looking for guidance on how to <TASK>.",
    "What steps do I need to take to <TASK>?",
    "Could you provide instructions for <TASK>?",
    "I'm wondering what the process is for <TASK>.",
    "How can I go about <TASK>?",
    "I need assistance with planning to <TASK>.",
    "Do you have any recommendations for <TASK>?",
    "Please share some tips for <TASK>.",
    "I'd like to know the best way to <TASK>.",
    "What's the most effective way to <TASK>?",
    "I'm seeking advice on accomplishing <TASK>.",
    "Could you guide me through the steps to <TASK>?",
    "I'm unsure how to start with <TASK>.",
    "Is there a strategy for successfully <TASK>?",
    "What's the proper procedure for <TASK>?",
    "How should I prepare for <TASK>?",
    "I'm not sure where to begin with <TASK>.",
    "I need some insights on <TASK>.",
    "Can you explain how to tackle <TASK>?",
    "I'm interested in the process of <TASK>.",
    "Could you enlighten me on <TASK>?",
    "What are the recommended steps for <TASK>?",
    "Is there a preferred method for <TASK>?",
    "I'd appreciate your advice on <TASK>.",
    "Can you shed light on <TASK>?",
    "What would be the best approach to <TASK>?",
    "How do I get started with <TASK>?",
    "I'm inquiring about the procedure for <TASK>.",
    "Could you share your expertise on <TASK>?",
    "I'd like some guidance on <TASK>.",
    "What's your recommendation for <TASK>?",
    "I'm seeking your input on how to <TASK>.",
    "Can you provide some insights into <TASK>?",
    "How can I successfully accomplish <TASK>?",
    "What steps are involved in <TASK>?",
    "I'm curious about the best way to <TASK>.",
    "Could you show me the ropes for <TASK>?",
    "I need to know how to go about <TASK>.",
    "What are the essential steps for <TASK>?",
    "Is there a specific method for <TASK>?",
    "I'd like to get some advice on <TASK>.",
    "Can you explain the process of <TASK>?",
    "I'm looking for guidance on how to approach <TASK>.",
    "What's the proper way to handle <TASK>?",
    "How should I proceed with <TASK>?",
    "I'm interested in your expertise on <TASK>.",
    "Could you walk me through the steps for <TASK>?",
    "I'm not sure where to begin when it comes to <TASK>.",
    "What should I prioritize when doing <TASK>?",
    "How can I ensure success with <TASK>?",
    "I'd appreciate some tips on <TASK>.",
    "Can you provide a roadmap for <TASK>?",
    "What's the recommended course of action for <TASK>?",
    "I'm seeking your guidance on <TASK>.",
    "Could you offer some suggestions for <TASK>?",
    "I'd like to know the steps to take for <TASK>.",
    "What's the most effective way to achieve <TASK>?",
    "How can I make the most of <TASK>?",
    "I'm wondering about the best approach to <TASK>.",
    "Can you share your insights on <TASK>?",
    "What steps should I follow to complete <TASK>?",
    "I'm looking for advice on <TASK>.",
    "What's the strategy for successfully completing <TASK>?",
    "How should I prepare myself for <TASK>?",
    "I'm not sure where to start with <TASK>.",
    "What's the procedure for <TASK>?",
    "Could you provide some guidance on <TASK>?",
    "I'd like to get some tips on how to <TASK>.",
    "Can you explain how to tackle <TASK> step by step?",
    "I'm interested in understanding the process of <TASK>.",
    "What are the key steps to <TASK>?",
    "Is there a specific method that works for <TASK>?",
    "I'd appreciate your advice on successfully completing <TASK>.",
    "Can you shed light on the best way to <TASK>?",
    "What would you recommend as the first step to <TASK>?",
    "How do I initiate <TASK>?",
    "I'm inquiring about the recommended steps for <TASK>.",
    "Could you share some insights into <TASK>?",
    "I'm seeking your expertise on <TASK>.",
    "What's your recommended approach for <TASK>?",
    "I'd like some guidance on where to start with <TASK>.",
    "Can you provide recommendations for <TASK>?",
    "What's your advice for someone looking to <TASK>?",
    "I'm seeking your input on the process of <TASK>.",
    "How can I achieve success with <TASK>?",
    "What's the best way to navigate <TASK>?",
    "I'm curious about the steps required for <TASK>.",
    "Could you show me the proper way to <TASK>?",
    "I need to know the necessary steps for <TASK>.",
    "What's the most efficient method for <TASK>?",
    "I'd appreciate your guidance on <TASK>.",
    "Can you explain the steps involved in <TASK>?",
    "I'm looking for recommendations on how to approach <TASK>.",
    "What's the right way to handle <TASK>?",
    "How should I manage <TASK>?",
    "I'm interested in your insights on <TASK>.",
    "Could you provide a step-by-step guide for <TASK>?",
    "I'm not sure how to start when it comes to <TASK>.",
    "What are the key factors to consider for <TASK>?",
    "How can I ensure a successful outcome with <TASK>?",
    "I'd like some tips and tricks for <TASK>.",
    "Can you offer a roadmap for accomplishing <TASK>?",
    "What's the preferred course of action for <TASK>?",
    "I'm seeking your expert advice on <TASK>.",
    "Could you suggest some best practices for <TASK>?",
    "I'd like to understand the necessary steps to complete <TASK>.",
    "What's the most effective strategy for <TASK>?",
]

question_en = ["<img><Image></img> {} A:",
                     "<img><Image></img> {} Answer:",
                     "<img><Image></img> {} The answer is:",
                     "<img><Image></img> {}",
                     "<img><Image></img> {}",
                     "<img><Image></img> Q: {} A:",
                     "<img><Image></img> Question: {} Answer:",
                     ]

question_cn = ["<img><Image></img> {} 答：",
                     "<img><Image></img> {} 答案是：",
                     "<img><Image></img> {}",
                     "<img><Image></img> {}",
                     "<img><Image></img> 问：{} 答：",
                     "<img><Image></img> 问：{} ",
                     "<img><Image></img> Q: {} A:",
                     "<img><Image></img> {} A:",
                     ]